# DECOUVERTE DE DONNES

In [2]:
import pandas as pd
import os

Chargement de données CSV de videos game sales

In [3]:
dossier = r'C:\Users\hp\Documents\training\training-data-science\games-sales\datasets'

In [4]:
chemin_fichier = dossier + '\\data_transforme.csv'

In [5]:
all_data = pd.read_csv(chemin_fichier)

In [6]:
all_data.head()

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,annees
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,2013
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2014
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,2002
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,2013
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2015

Création de Genre dans le colonne Dataframme

In [7]:
genre_list = all_data['genre'].unique()
genre_list

array(['Action', 'Shooter', 'Action-Adventure', 'Sports', 'Role-Playing',
       'Simulation', 'Racing', 'Music', 'Misc', 'Fighting', 'Platform',
       'Adventure', 'Strategy', 'Puzzle', 'MMO', 'Sandbox', 'Party',
       'Education', 'Board Game', 'Visual Novel'], dtype=object)

# Generer id liste des genres

In [8]:
genre_id_list = list(range(0, len(genre_list)))
genre_id_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Creation de genre Dataframe

In [9]:
genre_data = pd.DataFrame ({
    'genre_id': genre_id_list,
    'genre': genre_list
})
genre_data

    genre_id             genre
0          0            Action
1          1           Shooter
2          2  Action-Adventure
3          3            Sports
4          4      Role-Playing
5          5        Simulation
6          6            Racing
7          7             Music
8          8              Misc
9          9          Fighting
10        10          Platform
11        11         Adventure
12        12          Strategy
13        13            Puzzle
14        14               MMO
15        15           Sandbox
16        16             Party
17        17         Education
18        18        Board Game
19        19      Visual Novel

# Creation de DataFrame Devellopeur

 Vérifier les valeurs nulles dans la colonne 'developer'

In [10]:
null_value = all_data['developer'].isnull()
null_value

0        False
1        False
2        False
3        False
4        False
         ...
18917    False
18918    False
18919    False
18920    False
18921    False
Name: developer, Length: 18922, dtype: bool

Compter le nombre de valeurs nulles

In [11]:
count_null = null_value.sum()
count_null

4

Afficher les indices des lignes où la valeur est nulle

In [12]:
indices_null_values = all_data.index[null_value]
indices_null_values

Index([8486, 10832, 18185, 18455], dtype='int64')

Generer des listes uniques de developer

In [13]:
developer_list = all_data['developer'].dropna().unique()
developer_list

array(['Rockstar North', 'Treyarch', 'Infinity Ward', ...,
       'Snowberry Connection and Sich Studio',
       'Sigil Games Online/Sony Online Entertainment', 'TownFactory'],
      dtype=object)

Generer listes des id developer

In [14]:
developer_id_list = list(range(0, len(developer_list)))
developer_id_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

Creation de DataFrame developer id

In [15]:
developer_data = pd.DataFrame ({
    'developer_id' : developer_id_list,
    'developer': developer_list
})
developer_data

      developer_id                                     developer
0                0                                Rockstar North
1                1                                      Treyarch
2                2                                 Infinity Ward
3                3                                Rockstar Games
4                4                            Sledgehammer Games
...            ...                                           ...
2862          2862                                         Noise
2863          2863                   Digital Works Entertainment
2864          2864          Snowberry Connection and Sich Studio
2865          2865  Sigil Games Online/Sony Online Entertainment
2866          2866                                   TownFactory

[2867 rows x 2 columns]

In [16]:
developer_data.dtypes

developer_id     int64
developer       object
dtype: object

# Creation de DataFrame console

In [17]:
console_list = all_data['console'].unique()
console_list

array(['PS3', 'PS4', 'PS2', 'X360', 'XOne', 'PC', 'PSP', 'Wii', 'PS',
       'DS', '2600', 'GBA', 'NES', 'XB', 'PSN', 'GEN', 'PSV', 'DC', 'N64',
       'SAT', 'SNES', 'GBC', 'GC', 'NS', '3DS', 'GB', 'WiiU', 'WS', 'VC',
       'NG', 'WW', 'SCD', 'PCE', 'XBL', '3DO', 'GG', 'OSX', 'Mob', 'PCFX'],
      dtype=object)

In [18]:
console_id_list = list(range(0, len(console_list)))
console_id_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38]

In [19]:
console_data = pd.DataFrame({
    'console_id' : console_id_list,
    'console' : console_list
})
console_data

    console_id console
0            0     PS3
1            1     PS4
2            2     PS2
3            3    X360
4            4    XOne
5            5      PC
6            6     PSP
7            7     Wii
8            8      PS
9            9      DS
10          10    2600
11          11     GBA
12          12     NES
13          13      XB
14          14     PSN
15          15     GEN
16          16     PSV
17          17      DC
18          18     N64
19          19     SAT
20          20    SNES
21          21     GBC
22          22      GC
23          23      NS
24          24     3DS
25          25      GB
26          26    WiiU
27          27      WS
28          28      VC
29          29      NG
30          30      WW
31          31     SCD
32          32     PCE
33          33     XBL
34          34     3DO
35          35      GG
36          36     OSX
37          37     Mob
38          38    PCFX

In [20]:
console_data.dtypes

console_id     int64
console       object
dtype: object

# Creation de dataframe publisher

Generation de liste unique

In [21]:
publisher_list = all_data['publisher'].unique()
console_list

array(['PS3', 'PS4', 'PS2', 'X360', 'XOne', 'PC', 'PSP', 'Wii', 'PS',
       'DS', '2600', 'GBA', 'NES', 'XB', 'PSN', 'GEN', 'PSV', 'DC', 'N64',
       'SAT', 'SNES', 'GBC', 'GC', 'NS', '3DS', 'GB', 'WiiU', 'WS', 'VC',
       'NG', 'WW', 'SCD', 'PCE', 'XBL', '3DO', 'GG', 'OSX', 'Mob', 'PCFX'],
      dtype=object)

In [22]:
publisher_id_list = list(range(0, len(publisher_list)))
publisher_id_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738]

In [23]:
publisher_data = pd.DataFrame({
    'publisher_id' : publisher_id_list,
    'publisher' : publisher_list
})
publisher_data

     publisher_id                    publisher
0               0               Rockstar Games
1               1                   Activision
2               2                    EA Sports
3               3              Electronic Arts
4               4       Microsoft Game Studios
..            ...                          ...
734           734                   Noviy Disk
735           735                     Joindots
736           736            United Developers
737           737                        Stack
738           738  Digital Works Entertainment

[739 rows x 2 columns]

# Creation de Games dataframe

Generation de liste unique

In [24]:
game_id_list = list(range(0, len(all_data)))
game_id_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

Generer les liste ids du genre dans le dataframe

In [25]:
genre_id = []
for index, row in all_data.iterrows():
    genre_id.append((genre_data.loc[genre_data['genre'] == row[2]]['genre_id']).values[0])
genre_id

[0,
 0,
 0,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 3,
 0,
 3,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 4,
 0,
 1,
 4,
 3,
 1,
 3,
 5,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 6,
 6,
 7,
 1,
 0,
 1,
 3,
 3,
 0,
 0,
 2,
 4,
 8,
 3,
 0,
 1,
 8,
 2,
 1,
 9,
 0,
 5,
 0,
 0,
 0,
 6,
 1,
 8,
 10,
 4,
 2,
 0,
 11,
 3,
 1,
 1,
 1,
 5,
 8,
 3,
 3,
 4,
 0,
 3,
 0,
 4,
 4,
 3,
 12,
 8,
 0,
 4,
 3,
 1,
 0,
 10,
 1,
 6,
 0,
 0,
 0,
 6,
 3,
 0,
 0,
 6,
 8,
 3,
 3,
 1,
 8,
 1,
 3,
 0,
 4,
 3,
 3,
 1,
 6,
 8,
 1,
 1,
 2,
 1,
 0,
 1,
 8,
 0,
 0,
 3,
 9,
 3,
 1,
 10,
 0,
 3,
 1,
 3,
 0,
 1,
 3,
 0,
 5,
 4,
 8,
 1,
 0,
 3,
 6,
 8,
 9,
 4,
 4,
 3,
 8,
 0,
 1,
 2,
 3,
 7,
 3,
 3,
 8,
 11,
 5,
 10,
 3,
 3,
 3,
 5,
 6,
 1,
 1,
 10,
 3,
 3,
 8,
 6,
 1,
 1,
 0,
 1,
 0,
 9,
 5,
 0,
 11,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 3,
 3,
 9,
 3,
 1,
 1,
 3,
 8,
 9,
 11,
 1,
 10,
 3,
 0,
 1,
 0,
 3,
 8,
 1,
 4,
 0,
 9,
 2,
 3,
 1,
 0,
 1,
 3,
 0,
 3,
 6,
 1,
 0,
 3,
 11,
 1,
 9,
 2,
 0,
 2,
 4,
 3,
 11,
 3,
 0,
 4,
 0,
 6,
 1,
 1,
 3,
 4,
 11,
 3,
 0,
 1,
 5,
 1,
 11,
 10,
 0,
 4,
 10,
 0,
 9,
 8,
 3,
 1,
 0,
 1,
 9,
 9,
 13,
 3,
 1,
 3,
 4,
 9,
 1,
 5,
 3,
 3,
 5,
 6,
 2,
 4,
 0,
 3,
 1,
 9,
 3,
 4,
 10,
 6,
 1,
 5,
 6,
 1,
 3,
 0,
 9,
 9,
 3,
 10,
 0,
 0,
 5,
 1,
 6,
 2,
 11,
 1,
 6,
 1,
 3,
 3,
 3,
 1,
 0,
 3,
 6,
 9,
 1,
 1,
 4,
 1,
 8,
 9,
 0,
 6,
 0,
 1,
 3,
 6,
 3,
 3,
 3,
 3,
 3,
 10,
 11,
 11,
 0,
 3,
 3,
 1,
 0,
 9,
 8,
 3,
 3,
 4,
 3,
 3,
 3,
 6,
 0,
 6,
 3,
 4,
 0,
 9,
 8,
 3,
 0,
 0,
 3,
 8,
 0,
 8,
 6,
 11,
 0,
 3,
 6,
 8,
 5,
 1,
 10,
 6,
 1,
 2,
 6,
 3,
 3,
 6,
 6,
 2,
 6,
 13,
 3,
 12,
 3,
 11,
 8,
 9,
 0,
 9,
 0,
 3,
 3,
 3,
 8,
 1,
 11,
 0,
 9,
 4,
 3,
 3,
 0,
 3,
 0,
 3,
 6,
 5,
 0,
 1,
 0,
 11,
 11,
 3,
 6,
 3,
 3,
 1,
 1,
 2,
 3,
 8,
 8,
 3,
 10,
 1,
 5,
 0,
 10,
 11,
 3,
 1,
 0,
 3,
 8,
 3,
 8,
 11,
 6,
 1,
 3,
 13,
 3,
 10,
 3,
 4,
 4,
 1,
 6,
 6,
 6,
 1,
 10,
 3,
 5,
 8,
 1,
 1,
 1,
 5,
 3,
 5,
 1,
 1,
 9,
 3,
 6,
 3,
 3,
 10,
 1,
 0,
 3,
 11,
 6,
 7,
 13,
 0,
 8,
 12,
 8,
 1,
 9,
 1,
 5,
 11,
 5,
 1,
 6,
 0,
 0,
 0,
 0,
 6,
 3,
 4,
 9,
 14,
 6,
 3,
 1,
 4,
 6,
 6,
 3,
 7,
 8,
 0,
 0,
 3,
 3,
 3,
 8,
 5,
 3,
 3,
 8,
 6,
 1,
 13,
 1,
 0,
 11,
 9,
 11,
 2,
 0,
 0,
 0,
 1,
 10,
 3,
 0,
 1,
 3,
 1,
 0,
 1,
 6,
 6,
 11,
 1,
 1,
 9,
 6,
 8,
 6,
 3,
 4,
 9,
 9,
 5,
 11,
 8,
 1,
 1,
 6,
 0,
 3,
 6,
 5,
 0,
 2,
 8,
 3,
 8,
 15,
 3,
 9,
 8,
 1,
 9,
 3,
 8,
 0,
 8,
 4,
 10,
 11,
 0,
 10,
 0,
 1,
 3,
 3,
 0,
 10,
 6,
 8,
 3,
 6,
 8,
 6,
 4,
 2,
 1,
 10,
 8,
 1,
 4,
 5,
 6,
 5,
 10,
 3,
 3,
 10,
 8,
 6,
 0,
 10,
 0,
 0,
 6,
 0,
 0,
 0,
 5,
 0,
 9,
 4,
 10,
 10,
 9,
 1,
 9,
 8,
 5,
 0,
 0,
 3,
 3,
 8,
 1,
 5,
 3,
 11,
 3,
 3,
 9,
 2,
 10,
 0,
 0,
 3,
 1,
 1,
 9,
 3,
 13,
 8,
 3,
 0,
 1,
 13,
 6,
 8,
 1,
 10,
 5,
 1,
 1,
 13,
 3,
 3,
 0,
 0,
 3,
 5,
 5,
 5,
 1,
 0,
 2,
 0,
 8,
 9,
 4,
 6,
 1,
 1,
 8,
 1,
 5,
 0,
 4,
 10,
 3,
 3,
 1,
 6,
 11,
 6,
 1,
 3,
 3,
 9,
 8,
 3,
 3,
 3,
 3,
 3,
 6,
 5,
 0,
 13,
 11,
 3,
 2,
 3,
 1,
 1,
 4,
 13,
 3,
 10,
 3,
 1,
 0,
 1,
 3,
 6,
 1,
 3,
 8,
 5,
 8,
 3,
 11,
 1,
 1,
 6,
 3,
 1,
 1,
 0,
 10,
 3,
 9,
 6,
 11,
 1,
 10,
 3,
 3,
 0,
 5,
 10,
 8,
 0,
 8,
 8,
 3,
 0,
 3,
 1,
 8,
 3,
 0,
 9,
 6,
 0,
 5,
 0,
 9,
 1,
 1,
 1,
 1,
 8,
 1,
 6,
 0,
 6,
 1,
 3,
 4,
 8,
 3,
 9,
 3,
 8,
 3,
 3,
 5,
 13,
 9,
 9,
 6,
 6,
 6,
 6,
 11,
 1,
 1,
 3,
 3,
 10,
 10,
 1,
 1,
 3,
 0,
 0,
 3,
 1,
 2,
 9,
 8,
 10,
 8,
 0,
 6,
 3,
 3,
 9,
 9,
 1,
 10,
 3,
 0,
 0,
 0,
 4,
 3,
 3,
 1,
 8,
 11,
 12,
 11,
 11,
 3,
 0,
 9,
 8,
 1,
 0,
 8,
 1,
 0,
 9,
 10,
 8,
 13,
 5,
 8,
 9,
 10,
 0,
 9,
 1,
 4,
 3,
 5,
 6,
 4,
 1,
 13,
 10,
 3,
 1,
 1,
 5,
 1,
 6,
 5,
 9,
 8,
 8,
 6,
 11,
 8,
 0,
 3,
 1,
 0,
 3,
 8,
 6,
 4,
 3,
 8,
 1,
 9,
 10,
 0,
 8,
 9,
 3,
 2,
 3,
 9,
 1,
 0,
 3,
 3,
 8,
 3,
 0,
 11,
 0,
 8,
 6,
 6,
 0,
 9,
 3,
 6,
 10,
 0,
 6,
 12,
 9,
 1,
 0,
 2,
 1,
 0,
 0,
 9,
 10,
 3,
 3,
 5,
 0,
 3,
 5,
 1,
 14,
 1,
 1,
 3,
 0,
 10,
 1,
 1,
 0,
 11,
 6,
 1,
 1,
 6,
 3,
 1,
 4,
 8,
 11,
 0,
 10,
 10,
 3,
 1,
 9,
 1,
 1,
 1,
 1,
 1,
 8,
 8,
 13,
 0,
 3,
 3,
 3,
 11,
 3,
 5,
 3,
 6,
 6,
 8,
 1,
 6,
 1,
 10,
 9,
 3,
 11,
 1,
 6,
 6,
 12,
 1,
 0,
 9,
 9,
 0,
 0,
 1,
 10,
 5,
 6,
 ...]

Genererer les liste console ids dans le dataframe

In [26]:
console_id = []
for index, row in all_data.iterrows():
    console_id.append((console_data.loc[console_data['console'] == row[1]]['console_id']).values[0])
console_id

[0,
 1,
 2,
 3,
 1,
 3,
 3,
 1,
 3,
 0,
 3,
 1,
 0,
 2,
 0,
 1,
 3,
 1,
 0,
 0,
 3,
 0,
 3,
 3,
 3,
 1,
 1,
 3,
 4,
 1,
 1,
 1,
 1,
 0,
 5,
 6,
 1,
 3,
 4,
 3,
 1,
 0,
 2,
 2,
 7,
 2,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 1,
 1,
 8,
 4,
 0,
 4,
 1,
 8,
 7,
 9,
 0,
 3,
 0,
 3,
 0,
 4,
 2,
 0,
 3,
 3,
 8,
 2,
 4,
 2,
 4,
 5,
 2,
 3,
 9,
 3,
 0,
 0,
 6,
 1,
 4,
 8,
 8,
 2,
 0,
 3,
 2,
 4,
 0,
 1,
 4,
 8,
 9,
 3,
 8,
 2,
 8,
 2,
 8,
 3,
 7,
 0,
 7,
 1,
 3,
 1,
 2,
 2,
 3,
 2,
 2,
 1,
 2,
 7,
 1,
 3,
 1,
 10,
 0,
 0,
 11,
 0,
 3,
 2,
 0,
 3,
 1,
 12,
 8,
 3,
 4,
 2,
 1,
 1,
 2,
 1,
 5,
 3,
 7,
 1,
 1,
 2,
 3,
 8,
 2,
 0,
 5,
 1,
 2,
 1,
 1,
 0,
 2,
 7,
 0,
 2,
 8,
 3,
 5,
 6,
 4,
 2,
 2,
 9,
 6,
 2,
 0,
 2,
 2,
 0,
 7,
 2,
 2,
 5,
 1,
 2,
 4,
 8,
 9,
 2,
 8,
 2,
 3,
 3,
 3,
 3,
 2,
 2,
 8,
 3,
 1,
 1,
 2,
 3,
 3,
 9,
 9,
 2,
 3,
 4,
 0,
 1,
 8,
 4,
 2,
 2,
 8,
 4,
 1,
 1,
 8,
 3,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 6,
 0,
 2,
 4,
 0,
 8,
 8,
 1,
 2,
 1,
 0,
 2,
 9,
 4,
 8,
 0,
 0,
 8,
 1,
 4,
 3,
 3,
 7,
 2,
 3,
 4,
 5,
 3,
 9,
 3,
 1,
 3,
 8,
 13,
 2,
 5,
 2,
 3,
 2,
 0,
 3,
 2,
 11,
 3,
 1,
 3,
 3,
 0,
 2,
 7,
 3,
 2,
 9,
 8,
 1,
 13,
 0,
 3,
 3,
 2,
 7,
 1,
 11,
 14,
 0,
 9,
 0,
 0,
 2,
 7,
 2,
 8,
 8,
 8,
 3,
 3,
 2,
 5,
 0,
 1,
 3,
 4,
 1,
 4,
 3,
 0,
 3,
 3,
 2,
 3,
 2,
 15,
 8,
 2,
 0,
 6,
 3,
 2,
 2,
 0,
 9,
 3,
 3,
 2,
 1,
 0,
 3,
 2,
 1,
 6,
 2,
 3,
 15,
 0,
 2,
 4,
 3,
 2,
 7,
 2,
 3,
 3,
 8,
 0,
 3,
 2,
 0,
 0,
 2,
 3,
 13,
 2,
 7,
 1,
 0,
 8,
 4,
 3,
 4,
 16,
 3,
 7,
 1,
 4,
 8,
 7,
 2,
 3,
 17,
 6,
 3,
 3,
 2,
 0,
 4,
 2,
 4,
 0,
 3,
 8,
 0,
 5,
 3,
 11,
 5,
 15,
 3,
 18,
 2,
 0,
 3,
 2,
 0,
 4,
 7,
 3,
 2,
 1,
 3,
 3,
 8,
 7,
 4,
 8,
 8,
 3,
 0,
 2,
 0,
 5,
 9,
 0,
 13,
 2,
 0,
 2,
 0,
 1,
 1,
 0,
 7,
 8,
 11,
 7,
 2,
 12,
 11,
 2,
 4,
 1,
 0,
 0,
 3,
 1,
 3,
 9,
 3,
 3,
 12,
 9,
 4,
 7,
 0,
 13,
 3,
 1,
 1,
 2,
 1,
 4,
 1,
 7,
 5,
 1,
 8,
 1,
 6,
 5,
 0,
 2,
 10,
 0,
 3,
 18,
 2,
 0,
 3,
 2,
 4,
 2,
 3,
 0,
 6,
 7,
 2,
 6,
 7,
 5,
 7,
 3,
 3,
 8,
 7,
 1,
 9,
 3,
 8,
 11,
 9,
 0,
 3,
 0,
 12,
 0,
 0,
 1,
 3,
 15,
 2,
 1,
 3,
 0,
 4,
 3,
 9,
 1,
 2,
 0,
 2,
 0,
 7,
 0,
 4,
 1,
 3,
 0,
 3,
 9,
 0,
 8,
 11,
 3,
 8,
 1,
 1,
 10,
 3,
 3,
 2,
 6,
 0,
 0,
 2,
 3,
 13,
 5,
 2,
 0,
 8,
 2,
 7,
 2,
 3,
 3,
 8,
 3,
 2,
 19,
 20,
 5,
 21,
 0,
 4,
 2,
 2,
 1,
 4,
 3,
 22,
 3,
 3,
 7,
 0,
 7,
 23,
 8,
 2,
 7,
 2,
 8,
 8,
 2,
 0,
 2,
 8,
 9,
 21,
 1,
 2,
 7,
 0,
 2,
 13,
 9,
 2,
 4,
 7,
 2,
 2,
 11,
 8,
 4,
 0,
 0,
 15,
 2,
 3,
 24,
 5,
 17,
 2,
 2,
 0,
 8,
 11,
 2,
 1,
 7,
 20,
 8,
 2,
 2,
 4,
 2,
 2,
 2,
 11,
 0,
 0,
 2,
 15,
 2,
 13,
 8,
 7,
 2,
 0,
 1,
 8,
 2,
 11,
 13,
 2,
 0,
 8,
 4,
 4,
 4,
 1,
 11,
 8,
 25,
 2,
 3,
 2,
 1,
 2,
 7,
 9,
 13,
 2,
 1,
 11,
 13,
 7,
 0,
 8,
 9,
 5,
 16,
 20,
 2,
 7,
 9,
 3,
 2,
 5,
 9,
 24,
 2,
 11,
 3,
 3,
 8,
 18,
 11,
 3,
 6,
 8,
 2,
 4,
 5,
 0,
 0,
 2,
 2,
 8,
 13,
 13,
 11,
 2,
 0,
 2,
 8,
 0,
 7,
 7,
 2,
 3,
 2,
 2,
 3,
 7,
 7,
 10,
 2,
 2,
 4,
 2,
 8,
 3,
 1,
 10,
 2,
 8,
 13,
 3,
 16,
 1,
 2,
 8,
 5,
 2,
 0,
 3,
 2,
 2,
 9,
 4,
 1,
 2,
 4,
 3,
 10,
 3,
 10,
 0,
 8,
 8,
 3,
 3,
 0,
 2,
 3,
 4,
 7,
 11,
 8,
 0,
 9,
 9,
 2,
 7,
 2,
 2,
 9,
 7,
 8,
 0,
 2,
 9,
 9,
 3,
 2,
 4,
 18,
 0,
 13,
 7,
 0,
 2,
 8,
 3,
 8,
 1,
 2,
 7,
 2,
 20,
 8,
 3,
 8,
 0,
 7,
 22,
 8,
 0,
 6,
 8,
 4,
 8,
 9,
 12,
 3,
 2,
 8,
 2,
 9,
 0,
 7,
 4,
 0,
 2,
 8,
 5,
 1,
 8,
 8,
 12,
 0,
 8,
 2,
 2,
 5,
 18,
 22,
 2,
 1,
 8,
 0,
 3,
 0,
 1,
 2,
 0,
 13,
 2,
 16,
 9,
 9,
 9,
 2,
 3,
 2,
 7,
 3,
 13,
 3,
 3,
 4,
 3,
 11,
 26,
 9,
 9,
 2,
 8,
 9,
 11,
 8,
 3,
 0,
 8,
 7,
 4,
 0,
 3,
 22,
 10,
 2,
 2,
 4,
 25,
 7,
 7,
 25,
 20,
 6,
 18,
 6,
 9,
 9,
 3,
 2,
 0,
 4,
 2,
 2,
 3,
 1,
 8,
 7,
 0,
 3,
 11,
 8,
 7,
 3,
 7,
 7,
 2,
 0,
 0,
 4,
 12,
 2,
 7,
 2,
 6,
 7,
 22,
 9,
 2,
 2,
 15,
 8,
 8,
 2,
 11,
 13,
 2,
 5,
 3,
 3,
 7,
 4,
 5,
 12,
 7,
 1,
 3,
 20,
 8,
 1,
 9,
 4,
 6,
 3,
 4,
 8,
 3,
 2,
 13,
 16,
 0,
 0,
 0,
 0,
 0,
 7,
 3,
 3,
 0,
 4,
 13,
 8,
 2,
 7,
 3,
 11,
 0,
 7,
 0,
 13,
 1,
 10,
 12,
 2,
 7,
 2,
 9,
 4,
 0,
 8,
 6,
 7,
 6,
 8,
 3,
 13,
 3,
 2,
 0,
 0,
 2,
 22,
 15,
 2,
 0,
 13,
 2,
 2,
 5,
 0,
 3,
 0,
 18,
 0,
 3,
 0,
 2,
 11,
 2,
 ...]

Genererer les liste publisher ids dans le dataframe

In [27]:
publisher_id = []
for index, row in all_data.iterrows():
    publisher_id.append((publisher_data.loc[publisher_data['publisher'] == row[3]]['publisher_id']).values[0])
publisher_id

[0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 3,
 1,
 0,
 1,
 1,
 4,
 5,
 1,
 1,
 3,
 6,
 0,
 1,
 6,
 2,
 3,
 2,
 3,
 0,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 7,
 3,
 8,
 1,
 2,
 2,
 0,
 0,
 7,
 6,
 8,
 2,
 9,
 1,
 10,
 0,
 1,
 11,
 12,
 13,
 7,
 7,
 14,
 4,
 1,
 5,
 15,
 16,
 7,
 7,
 17,
 2,
 1,
 3,
 3,
 18,
 19,
 2,
 20,
 4,
 21,
 2,
 0,
 16,
 6,
 1,
 17,
 19,
 8,
 6,
 2,
 1,
 7,
 1,
 1,
 8,
 12,
 14,
 22,
 23,
 1,
 3,
 17,
 5,
 19,
 2,
 20,
 24,
 19,
 3,
 2,
 1,
 25,
 1,
 26,
 7,
 3,
 7,
 7,
 1,
 7,
 22,
 17,
 1,
 11,
 7,
 7,
 2,
 21,
 2,
 1,
 27,
 28,
 2,
 3,
 2,
 7,
 1,
 2,
 14,
 3,
 6,
 29,
 7,
 7,
 26,
 4,
 11,
 11,
 6,
 6,
 30,
 11,
 7,
 3,
 7,
 1,
 7,
 8,
 26,
 11,
 12,
 3,
 8,
 3,
 2,
 1,
 3,
 0,
 8,
 3,
 8,
 26,
 2,
 1,
 3,
 12,
 9,
 7,
 12,
 7,
 31,
 13,
 8,
 17,
 0,
 3,
 17,
 21,
 7,
 17,
 3,
 31,
 2,
 30,
 32,
 2,
 33,
 3,
 20,
 1,
 11,
 14,
 5,
 8,
 2,
 0,
 1,
 1,
 2,
 8,
 5,
 6,
 7,
 34,
 7,
 30,
 3,
 12,
 0,
 2,
 3,
 2,
 8,
 7,
 1,
 2,
 0,
 3,
 31,
 7,
 22,
 7,
 6,
 2,
 35,
 2,
 1,
 6,
 21,
 3,
 7,
 3,
 30,
 3,
 14,
 2,
 31,
 1,
 3,
 33,
 14,
 1,
 36,
 3,
 7,
 7,
 31,
 3,
 26,
 7,
 17,
 3,
 21,
 31,
 11,
 2,
 6,
 2,
 4,
 32,
 1,
 13,
 20,
 8,
 7,
 8,
 33,
 6,
 7,
 2,
 33,
 31,
 13,
 24,
 31,
 8,
 3,
 7,
 3,
 8,
 37,
 1,
 31,
 38,
 8,
 8,
 12,
 31,
 3,
 3,
 3,
 7,
 0,
 24,
 3,
 7,
 2,
 2,
 2,
 1,
 12,
 2,
 3,
 39,
 3,
 1,
 16,
 3,
 1,
 31,
 7,
 3,
 40,
 3,
 30,
 0,
 30,
 30,
 2,
 20,
 2,
 8,
 3,
 0,
 20,
 3,
 2,
 7,
 12,
 31,
 1,
 2,
 30,
 3,
 8,
 2,
 2,
 34,
 16,
 0,
 26,
 1,
 0,
 38,
 38,
 30,
 31,
 17,
 2,
 41,
 7,
 10,
 35,
 14,
 14,
 2,
 8,
 31,
 3,
 7,
 20,
 3,
 5,
 5,
 3,
 26,
 30,
 8,
 5,
 32,
 0,
 42,
 2,
 3,
 13,
 26,
 28,
 34,
 43,
 31,
 31,
 2,
 2,
 1,
 20,
 1,
 12,
 32,
 31,
 3,
 5,
 2,
 25,
 7,
 7,
 44,
 3,
 3,
 12,
 3,
 43,
 17,
 14,
 26,
 3,
 3,
 2,
 12,
 33,
 45,
 2,
 19,
 7,
 8,
 20,
 1,
 26,
 27,
 46,
 7,
 3,
 3,
 12,
 30,
 19,
 2,
 41,
 12,
 3,
 33,
 47,
 35,
 2,
 1,
 26,
 12,
 16,
 1,
 3,
 8,
 3,
 5,
 1,
 7,
 48,
 49,
 44,
 3,
 1,
 48,
 30,
 26,
 50,
 33,
 32,
 1,
 3,
 26,
 30,
 31,
 3,
 31,
 2,
 0,
 3,
 7,
 31,
 26,
 41,
 3,
 1,
 51,
 31,
 52,
 26,
 16,
 3,
 1,
 11,
 31,
 35,
 16,
 7,
 3,
 11,
 53,
 38,
 6,
 3,
 39,
 8,
 16,
 4,
 3,
 30,
 18,
 54,
 32,
 7,
 3,
 2,
 2,
 7,
 3,
 30,
 55,
 7,
 3,
 1,
 38,
 3,
 1,
 3,
 38,
 3,
 16,
 6,
 22,
 21,
 33,
 23,
 8,
 32,
 1,
 37,
 7,
 0,
 12,
 23,
 3,
 31,
 7,
 1,
 37,
 5,
 1,
 8,
 3,
 1,
 20,
 34,
 3,
 56,
 1,
 3,
 31,
 31,
 32,
 2,
 3,
 12,
 16,
 32,
 35,
 2,
 3,
 57,
 8,
 38,
 38,
 3,
 31,
 2,
 35,
 8,
 8,
 8,
 20,
 56,
 6,
 1,
 12,
 0,
 2,
 2,
 35,
 8,
 5,
 7,
 2,
 58,
 31,
 8,
 6,
 7,
 33,
 20,
 11,
 3,
 16,
 3,
 20,
 26,
 8,
 30,
 44,
 20,
 1,
 7,
 12,
 59,
 31,
 8,
 0,
 7,
 46,
 0,
 12,
 31,
 31,
 21,
 31,
 20,
 3,
 7,
 34,
 35,
 3,
 16,
 7,
 2,
 26,
 31,
 12,
 26,
 2,
 12,
 30,
 30,
 32,
 16,
 46,
 44,
 3,
 37,
 6,
 1,
 32,
 8,
 14,
 60,
 2,
 0,
 3,
 31,
 3,
 41,
 51,
 1,
 7,
 1,
 1,
 61,
 2,
 1,
 62,
 16,
 3,
 3,
 55,
 56,
 8,
 3,
 32,
 43,
 8,
 31,
 63,
 3,
 12,
 11,
 64,
 7,
 3,
 31,
 3,
 31,
 3,
 1,
 12,
 4,
 31,
 38,
 1,
 37,
 2,
 2,
 35,
 7,
 37,
 30,
 38,
 2,
 3,
 3,
 12,
 22,
 7,
 2,
 7,
 2,
 65,
 3,
 66,
 22,
 2,
 8,
 20,
 0,
 8,
 8,
 2,
 3,
 1,
 1,
 41,
 4,
 8,
 37,
 31,
 7,
 6,
 0,
 2,
 6,
 1,
 16,
 22,
 26,
 11,
 2,
 14,
 7,
 20,
 20,
 2,
 32,
 26,
 46,
 8,
 21,
 35,
 1,
 2,
 35,
 26,
 52,
 1,
 54,
 8,
 14,
 0,
 35,
 3,
 33,
 2,
 3,
 3,
 6,
 7,
 1,
 33,
 22,
 1,
 3,
 67,
 30,
 8,
 53,
 2,
 68,
 2,
 35,
 44,
 36,
 3,
 20,
 2,
 2,
 20,
 2,
 5,
 2,
 35,
 11,
 3,
 3,
 2,
 3,
 3,
 1,
 1,
 2,
 12,
 11,
 2,
 1,
 16,
 1,
 28,
 69,
 41,
 11,
 64,
 2,
 20,
 31,
 11,
 31,
 7,
 38,
 36,
 21,
 33,
 3,
 2,
 2,
 3,
 8,
 7,
 14,
 31,
 31,
 30,
 12,
 2,
 35,
 1,
 7,
 20,
 7,
 32,
 2,
 31,
 57,
 14,
 7,
 38,
 31,
 31,
 31,
 38,
 3,
 3,
 2,
 3,
 5,
 3,
 31,
 20,
 70,
 1,
 0,
 6,
 71,
 20,
 20,
 71,
 71,
 20,
 11,
 20,
 35,
 7,
 12,
 2,
 33,
 7,
 2,
 8,
 4,
 7,
 2,
 3,
 3,
 31,
 56,
 28,
 3,
 32,
 2,
 32,
 2,
 31,
 3,
 32,
 47,
 37,
 7,
 1,
 12,
 12,
 17,
 13,
 2,
 8,
 59,
 2,
 8,
 3,
 31,
 1,
 72,
 7,
 2,
 3,
 35,
 7,
 3,
 26,
 35,
 21,
 20,
 34,
 2,
 3,
 1,
 55,
 3,
 16,
 6,
 9,
 3,
 34,
 1,
 8,
 7,
 16,
 21,
 14,
 53,
 1,
 3,
 3,
 30,
 3,
 12,
 1,
 12,
 56,
 1,
 46,
 3,
 1,
 21,
 7,
 6,
 22,
 26,
 11,
 3,
 8,
 13,
 7,
 31,
 2,
 2,
 35,
 2,
 26,
 2,
 23,
 3,
 8,
 3,
 72,
 0,
 56,
 68,
 3,
 8,
 1,
 22,
 3,
 3,
 7,
 21,
 31,
 34,
 43,
 4,
 3,
 8,
 3,
 29,
 ...]

Genererer les liste devellopeur ids dans le dataframe

In [28]:
developer_id = []
for index, row in all_data.iterrows():
    if str(row[4]) == 'nan':
        developer_id.append(pd.NA)
    else:
        developer_id.append((developer_data.loc[developer_data['developer'] == row[4]]['developer_id']).values[0])
developer_id

[0,
 0,
 0,
 0,
 1,
 2,
 1,
 3,
 1,
 1,
 2,
 4,
 2,
 5,
 1,
 6,
 0,
 7,
 2,
 0,
 2,
 2,
 8,
 9,
 2,
 1,
 10,
 11,
 0,
 2,
 11,
 7,
 12,
 7,
 13,
 14,
 4,
 1,
 1,
 15,
 12,
 15,
 16,
 16,
 17,
 18,
 19,
 2,
 7,
 7,
 20,
 20,
 21,
 11,
 22,
 7,
 23,
 4,
 22,
 3,
 8,
 24,
 25,
 26,
 21,
 21,
 27,
 28,
 1,
 22,
 25,
 29,
 21,
 21,
 30,
 31,
 4,
 18,
 12,
 32,
 33,
 7,
 34,
 35,
 36,
 7,
 14,
 29,
 11,
 37,
 38,
 39,
 19,
 11,
 31,
 1,
 21,
 40,
 2,
 19,
 25,
 27,
 23,
 41,
 37,
 42,
 30,
 43,
 40,
 7,
 34,
 44,
 45,
 12,
 31,
 1,
 46,
 37,
 47,
 48,
 7,
 49,
 21,
 50,
 21,
 51,
 27,
 50,
 52,
 21,
 21,
 7,
 53,
 7,
 2,
 54,
 55,
 7,
 12,
 31,
 21,
 8,
 56,
 27,
 57,
 58,
 59,
 21,
 21,
 47,
 28,
 24,
 24,
 11,
 11,
 60,
 61,
 17,
 12,
 21,
 37,
 62,
 63,
 47,
 24,
 25,
 57,
 64,
 7,
 7,
 37,
 13,
 14,
 65,
 12,
 19,
 54,
 7,
 40,
 41,
 66,
 67,
 68,
 66,
 21,
 69,
 26,
 70,
 30,
 14,
 12,
 27,
 36,
 21,
 25,
 13,
 71,
 7,
 60,
 72,
 7,
 73,
 74,
 34,
 40,
 24,
 25,
 9,
 75,
 7,
 5,
 8,
 1,
 7,
 76,
 77,
 46,
 17,
 78,
 21,
 60,
 76,
 79,
 80,
 31,
 81,
 31,
 82,
 21,
 83,
 7,
 84,
 85,
 69,
 21,
 86,
 68,
 58,
 7,
 87,
 6,
 37,
 88,
 36,
 7,
 62,
 89,
 60,
 90,
 25,
 10,
 91,
 2,
 57,
 73,
 25,
 83,
 92,
 93,
 49,
 17,
 69,
 57,
 47,
 21,
 94,
 74,
 53,
 69,
 52,
 31,
 67,
 7,
 90,
 72,
 95,
 26,
 96,
 97,
 98,
 99,
 100,
 46,
 21,
 31,
 101,
 69,
 102,
 44,
 40,
 82,
 18,
 103,
 104,
 105,
 106,
 107,
 69,
 71,
 108,
 25,
 109,
 91,
 110,
 15,
 104,
 21,
 84,
 44,
 111,
 21,
 16,
 31,
 31,
 1,
 25,
 31,
 104,
 112,
 113,
 1,
 29,
 56,
 37,
 69,
 17,
 114,
 115,
 18,
 60,
 116,
 60,
 60,
 7,
 60,
 31,
 117,
 76,
 0,
 34,
 7,
 7,
 48,
 25,
 69,
 107,
 31,
 60,
 90,
 108,
 7,
 31,
 118,
 119,
 20,
 54,
 120,
 0,
 121,
 122,
 60,
 91,
 30,
 31,
 33,
 21,
 88,
 123,
 25,
 124,
 31,
 125,
 102,
 57,
 21,
 126,
 16,
 9,
 127,
 16,
 54,
 60,
 128,
 28,
 129,
 20,
 130,
 31,
 131,
 102,
 54,
 132,
 112,
 124,
 133,
 134,
 31,
 31,
 37,
 135,
 8,
 25,
 25,
 136,
 90,
 137,
 31,
 5,
 17,
 21,
 138,
 7,
 139,
 25,
 13,
 124,
 30,
 25,
 54,
 16,
 7,
 31,
 66,
 73,
 140,
 31,
 45,
 62,
 141,
 142,
 143,
 47,
 54,
 61,
 21,
 10,
 12,
 109,
 60,
 33,
 31,
 33,
 25,
 104,
 144,
 24,
 145,
 7,
 146,
 54,
 147,
 29,
 8,
 111,
 128,
 111,
 148,
 107,
 17,
 57,
 149,
 150,
 12,
 151,
 57,
 60,
 47,
 152,
 73,
 72,
 110,
 153,
 54,
 60,
 134,
 12,
 25,
 31,
 0,
 16,
 62,
 154,
 92,
 33,
 131,
 155,
 156,
 157,
 158,
 159,
 119,
 57,
 2,
 24,
 160,
 71,
 94,
 21,
 6,
 24,
 161,
 162,
 163,
 16,
 78,
 65,
 29,
 164,
 16,
 60,
 33,
 59,
 165,
 49,
 31,
 7,
 16,
 62,
 139,
 60,
 166,
 62,
 16,
 1,
 167,
 13,
 168,
 76,
 162,
 169,
 170,
 171,
 51,
 36,
 172,
 173,
 97,
 25,
 1,
 7,
 21,
 0,
 109,
 40,
 104,
 174,
 175,
 143,
 176,
 177,
 132,
 125,
 7,
 120,
 178,
 179,
 57,
 180,
 37,
 12,
 91,
 128,
 25,
 31,
 114,
 181,
 119,
 129,
 182,
 31,
 183,
 88,
 97,
 184,
 185,
 18,
 186,
 7,
 145,
 187,
 188,
 189,
 126,
 180,
 190,
 191,
 192,
 193,
 7,
 31,
 194,
 19,
 177,
 62,
 31,
 82,
 34,
 125,
 46,
 21,
 172,
 126,
 52,
 156,
 29,
 57,
 118,
 47,
 195,
 60,
 196,
 142,
 39,
 197,
 25,
 198,
 199,
 70,
 20,
 21,
 200,
 201,
 109,
 202,
 157,
 36,
 134,
 126,
 203,
 175,
 204,
 145,
 57,
 170,
 21,
 31,
 47,
 205,
 66,
 47,
 7,
 206,
 60,
 60,
 72,
 207,
 40,
 208,
 209,
 7,
 171,
 210,
 72,
 97,
 185,
 211,
 31,
 0,
 89,
 212,
 16,
 33,
 156,
 25,
 213,
 2,
 214,
 215,
 7,
 216,
 87,
 94,
 10,
 139,
 217,
 218,
 65,
 209,
 25,
 91,
 219,
 133,
 220,
 6,
 210,
 24,
 221,
 21,
 57,
 91,
 90,
 134,
 31,
 45,
 66,
 164,
 145,
 222,
 8,
 7,
 10,
 223,
 132,
 21,
 7,
 60,
 121,
 7,
 16,
 13,
 192,
 224,
 21,
 7,
 21,
 13,
 210,
 225,
 226,
 51,
 13,
 227,
 60,
 193,
 228,
 229,
 31,
 7,
 1,
 37,
 33,
 230,
 231,
 31,
 232,
 62,
 233,
 20,
 31,
 67,
 234,
 170,
 51,
 54,
 24,
 42,
 25,
 21,
 126,
 60,
 7,
 27,
 159,
 61,
 219,
 36,
 209,
 235,
 236,
 25,
 54,
 237,
 40,
 59,
 125,
 72,
 20,
 238,
 13,
 239,
 223,
 12,
 76,
 171,
 240,
 40,
 144,
 23,
 40,
 104,
 112,
 60,
 241,
 242,
 7,
 179,
 10,
 132,
 243,
 54,
 13,
 244,
 245,
 7,
 135,
 42,
 28,
 42,
 246,
 24,
 247,
 248,
 106,
 13,
 209,
 1,
 1,
 31,
 109,
 24,
 7,
 1,
 119,
 206,
 249,
 250,
 33,
 24,
 251,
 10,
 34,
 133,
 24,
 91,
 49,
 184,
 252,
 253,
 239,
 147,
 31,
 31,
 18,
 231,
 17,
 254,
 255,
 232,
 256,
 25,
 257,
 258,
 1,
 259,
 135,
 62,
 124,
 223,
 174,
 88,
 260,
 261,
 61,
 133,
 134,
 262,
 76,
 74,
 93,
 1,
 139,
 177,
 90,
 263,
 244,
 218,
 37,
 20,
 67,
 264,
 34,
 96,
 264,
 265,
 34,
 52,
 135,
 87,
 21,
 109,
 13,
 266,
 68,
 31,
 188,
 267,
 268,
 1,
 183,
 247,
 136,
 218,
 269,
 18,
 72,
 31,
 25,
 7,
 270,
 271,
 165,
 24,
 31,
 49,
 272,
 25,
 25,
 25,
 273,
 31,
 274,
 198,
 10,
 275,
 6,
 142,
 1,
 99,
 276,
 7,
 13,
 71,
 68,
 12,
 54,
 71,
 36,
 126,
 78,
 10,
 57,
 261,
 166,
 57,
 207,
 163,
 277,
 89,
 278,
 83,
 75,
 21,
 207,
 253,
 25,
 279,
 1,
 280,
 16,
 60,
 89,
 58,
 281,
 25,
 282,
 132,
 40,
 7,
 76,
 36,
 175,
 233,
 51,
 54,
 24,
 183,
 188,
 283,
 17,
 132,
 31,
 7,
 182,
 7,
 47,
 7,
 41,
 284,
 188,
 74,
 285,
 80,
 286,
 179,
 10,
 287,
 40,
 288,
 16,
 198,
 21,
 36,
 136,
 289,
 91,
 80,
 280,
 290,
 209,
 291,
 ...]

In [29]:
all_data.columns

Index(['title', 'console', 'genre', 'publisher', 'developer', 'critic_score',
       'total_sales', 'na_sales', 'jp_sales', 'pal_sales', 'other_sales',
       'release_date', 'annees'],
      dtype='object')

In [30]:
games_data = pd.DataFrame({
    'game_id' : game_id_list,
    'title' : all_data['title'],
    'annees' : all_data['annees'],
    'release_date' : all_data['release_date'],
    'critic_score' : all_data['critic_score'],
    'genre_id' : genre_id,
    'console_id' : console_id,
    'publisher_id' : publisher_id,
    'developer_id' : developer_id
})
games_data

,game_id,title,annees,release_date,critic_score,genre_id,console_id,publisher_id,developer_id
0,0,Grand Theft Auto V,2013,2013-09-17,9.4,0,0,0,0
1,1,Grand Theft Auto V,2014,2014-11-18,9.7,0,1,0,0
2,2,Grand Theft Auto: Vice City,2002,2002-10-28,9.6,0,2,0,0
3,3,Grand Theft Auto V,2013,2013-09-17,NaN,0,3,0,0
4,4,Call of Duty: Black Ops 3,2015,2015-11-06,8.1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
18917,18917,Teslagrad,2014,2014-09-11,7.0,10,26,669,2655
18918,18918,Open Season,2006,2006-09-19,6.4,10,13,7,21
18919,18919,The SpongeBob SquarePants Movie,2004,2004-10-27,6.0,10,5,31,134
18920,18920,Santa Claus Saves the Earth,2002,2002-10-30,NaN,10,11,167,1461
18921,18921,Fossil League: Dino Tournament Championship,2007,2007-01-22,NaN,4,9,62,261

In [31]:
games_data.dtypes

game_id           int64
title            object
annees            int64
release_date     object
critic_score    float64
genre_id          int64
console_id        int64
publisher_id      int64
developer_id     object
dtype: object

In [32]:
games_data["release_date"] = games_data["release_date"].astype('datetime64[ns]')
games_data["developer_id"] = games_data["developer_id"].astype("Int64")

In [33]:
games_data.dtypes

game_id                  int64
title                   object
annees                   int64
release_date    datetime64[ns]
critic_score           float64
genre_id                 int64
console_id               int64
publisher_id             int64
developer_id             Int64
dtype: object

In [34]:
games_data

,game_id,title,annees,release_date,critic_score,genre_id,console_id,publisher_id,developer_id
0,0,Grand Theft Auto V,2013,2013-09-17,9.4,0,0,0,0
1,1,Grand Theft Auto V,2014,2014-11-18,9.7,0,1,0,0
2,2,Grand Theft Auto: Vice City,2002,2002-10-28,9.6,0,2,0,0
3,3,Grand Theft Auto V,2013,2013-09-17,NaN,0,3,0,0
4,4,Call of Duty: Black Ops 3,2015,2015-11-06,8.1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
18917,18917,Teslagrad,2014,2014-09-11,7.0,10,26,669,2655
18918,18918,Open Season,2006,2006-09-19,6.4,10,13,7,21
18919,18919,The SpongeBob SquarePants Movie,2004,2004-10-27,6.0,10,5,31,134
18920,18920,Santa Claus Saves the Earth,2002,2002-10-30,NaN,10,11,167,1461
18921,18921,Fossil League: Dino Tournament Championship,2007,2007-01-22,NaN,4,9,62,261

Création de dataframe Sales pour les articles vendus

In [35]:
sales_data = pd.DataFrame({
    'game_id': game_id_list,
    'na_sales_in_millions': all_data['na_sales'],
    'pal_sales_in_millions': all_data['pal_sales'],
    'japan_sales_in_millions':all_data['jp_sales'],
    'other_sales_in_millions': all_data['other_sales'],
    'total_sales_in_millions': all_data['total_sales']})
sales_data

,game_id,na_sales_in_millions,pal_sales_in_millions,japan_sales_in_millions,other_sales_in_millions,total_sales_in_millions
0,0,6.37,9.85,0.99,3.12,20.32
1,1,6.06,9.71,0.60,3.02,19.39
2,2,8.41,5.49,0.47,1.78,16.15
3,3,9.06,5.33,0.06,1.42,15.86
4,4,6.18,6.05,0.41,2.44,15.09
...,...,...,...,...,...,...
18917,18917,NaN,0.00,NaN,0.00,0.00
18918,18918,0.00,0.00,NaN,0.00,0.00
18919,18919,0.00,NaN,NaN,0.00,0.00
18920,18920,0.00,0.00,NaN,0.00,0.00
18921,18921,0.00,NaN,NaN,0.00,0.00

In [36]:
sales_data.dtypes

game_id                      int64
na_sales_in_millions       float64
pal_sales_in_millions      float64
japan_sales_in_millions    float64
other_sales_in_millions    float64
total_sales_in_millions    float64
dtype: object

# Sauvegarder les dataframes en formats CSV

In [37]:
genre_data.to_excel('datasets/genre_data.xlsx', index=False)
console_data.to_excel('datasets/console_data.xlsx', index=False)
publisher_data.to_excel('datasets/publisher_data.xlsx', index=False)
developer_data.to_excel('datasets/developer_data.xlsx', index=False)
games_data.to_excel('datasets/games_data.xlsx', index=False)
sales_data.to_excel('datasets/sales_data.xlsx', index=False)